learning_log/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include(('learning_logs.urls', "learning_logs"), namespace='learning_logs')),
    url(r'^users/', include(('users.urls', "users"), namespace='users'))
    #r: raw string
    #include(): include another urlConf, in this case it is learning_logs app
]

learning_logs/urls.py
"""define URL patterns for learning_logs"""

from django.conf.urls import url
from . import views     #import views in the same directory

urlpatterns = [
    #home page
    url(r'^$', views.index, name='index'),
    # r: raw string
    # ^: url starts
    # $: url ends
    # r'^$': means nothing between start and end of the url 
    # views.index: index is a function to call
    # name: for other sections/pages to refer to

    # Show all topics
    url(r'^topics/$', views.topics, name='topics'),

    # detail page for a single topic
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),

    # page for adding a new topic
    url(r'^new_topic/$', views.new_topic, name='new_topic'),

    # page to add a new entry
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),

    # edit an entry
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry')
]

users/urls.py
from django.conf.urls import url 
from django.contrib.auth.views import login

from . import views

urlpatterns = [
  #login page
  url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),

  # logout page
  url(r'^logout/$', views.logout_view, name='logout'),

  # registration page
  url(r'^register/$', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """return a string representation of the model"""
        return self.text

class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:     #extra information to manage a model
        verbose_name_plural = 'entries'     # use entries when it needs to refer to more than one entry

    def __str__(self):
        return self.text[:50] + "..."   #show first 50 chars

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm): # inherit from forms.ModelForm
  class Meta:
    model = Topic                 # what model to base from
    fields = ['text']             # what field to include in the form
    labels = {'text': ''}         # do not generate a label for above text field


class EntryForm(forms.ModelForm):
  class Meta:
    model = Entry
    fields = ['text']
    labels = {'text': ''}
    widgets = {'text': forms.Textarea(attrs={'cols':100})}
    # override Django's default widget definition and customize element

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404    #redirect page
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

def index(request):
    """home page"""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """topics page"""
    topics = Topic.objects.order_by('date_added')
    # topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics':topics}
    return render(request, 'learning_logs/topics.html', context)
# A context is a
# dictionary in which the keys are names we’ll use in the template to access
# the data and the values are the data we need to send to the template. In this
# case, there’s one key-value pair, which contains the set of topics we’ll display
# on the page. When building a page that uses data, we pass the context variable
# to render() as well as the request object and the path to the template 

@login_required
def topic(request, topic_id):
    """topic page"""
    topic = Topic.objects.get(id=topic_id)
    # make sure topic belongs to its owner
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic, 'entries':entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):         # submit form and return to topics page
    """add a new topic"""
    if request.method != 'POST':
        # No data submitted; create a blank form
        # GET request to get new form initially
        form = TopicForm()  
    else:
        # POST data submitted; process data
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False) # save data to DB
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics')) # return to topics page
    
    context = {'form':form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """add a new entry"""
    topic = Topic.objects.get(id = topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False) # return an entry object
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id])) # pass topic_id as arg 
    context = {'form': form, 'topic': topic}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """edit an entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # make sure topic belongs to its owner
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry)    # initial request to load entry
    else:
        form = EntryForm(instance=entry, data=request.POST) # load entry to be edited
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))
    context={'entry':entry, 'topic':topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)
    

users/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm

def logout_view(request):
  """log out user"""
  logout(request)
  return HttpResponseRedirect(reverse('users:login'))

def register(request):
  """register a user"""
  if request.method != 'POST':
    form = UserCreationForm()
  else:
    form = UserCreationForm(data=request.POST)

    if form.is_valid():
      # save user
      new_user = form.save() # return a user object
      # log in and redirect to index page
      authenticate_user = authenticate(username=new_user, # return authenticated user object
        password=request.POST['password1']) # password1 should be the value of 1st input
      login(request, authenticate_user)
      return HttpResponseRedirect(reverse('learning_logs:index'))

  context = {'form': form}
  return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <title>Learning Log</title>
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>

    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    </button>
                    <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
                        Learning Log</a>
                </div>
                
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
                    </ul>
                
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li><a>Hello, {{ user.username }}.</a></li>
                            <li><a href="{% url 'users:logout' %}">Log out</a></li>
                        {% else %}
                            <li><a href="{% url 'users:register' %}">Register</a></li>
                            <li><a href="{% url 'users:login' %}">Log in</a></li>
                        {% endif %}
                    </ul>
                </div><!--/.nav-collapse -->
                
            </div>
        </nav>

        <div class="container">
            <div class="page-header">
                {% block header %}{% endblock header %}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>
        </div> <!-- /container -->

    </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></p>
  <p>Edit an entry:</p>
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button name="submit">Save changes</button>
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}
{% block header %}
  <div class='jumbotron'>
    <h1>Track your learning.</h1>
  </div>
{% endblock header %}

{% block content %}
  <h4>
    <a href="{% url 'users:register' %}">Register an account</a> to make
    your own Learning Log, and list the topics you're learning about.
  </h4>
  <h4>
    Whenever you learn something new about a topic, make an entry
    summarizing what you've learned.
  </h4>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></p>
  <p>Create a new entry:</p>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button name="submit">Add entry</button>
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}
{% block header %}
 <h3>Add a new topic:</h2>
{% endblock header %}

{% block content %}
  <form action="{% url 'learning_logs:new_topic' %}" method="POST" class="form">
    {% csrf_token %}

    {% bootstrap_form form %}

    {% buttons %}
      <button name='submit'>Add topic</button>
    {% endbuttons %}
    
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block header %}
  <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
  <a href="{% url 'learning_logs:new_entry' topic.id %}">Add a new entry</a>

  {% for entry in entries %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
          {{ entry.date_added|date:'M d, Y H:i'}}
          <small>
            <a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a>
          </small>
        </h3>
      </div>
      <div class="panel-body">
        {{ entry.text|linebreaks }}
      </div>
    </div><!--panel-->

  {% empty %}
    <li>
      There are no entries for this topic yet
    </li>
  {% endfor %}
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block header %}
  <h3>Topics</h3>
{% endblock header %}

{% block content %}

  <ul>
    {% for topic in topics %}
      <li>
        <h4><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></h4>
      </li>
    {% empty %}
      <li>No topics have been added yet</li>
    {% endfor %}
  </ul>
<h4><a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a></h4>
{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
 <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}
<!-- removed;bootstrap manage erros automatically -->
  <!-- {% if form.errors %} 
  <p>Please check your username and password</p>
  {% endif %} -->

  <form action="{% url 'users:login' %}" method="POST" class="form">
    {% csrf_token %}
    <!-- {{ form.as_p }} -->
    <!-- repalced with:  -->
    {% bootstrap_form form %} 

    {% buttons %}
      <button name="submit" class="btn btn-primary">Log in</button>
    {% endbuttons %}
    <input type="hidden" name='next' value="{% url 'learning_logs:index' %}">
  </form>

{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% block content %}
  <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">register</button>
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
 </form>

{% endblock content %}